In [15]:
import tensorflow_hub as hub
import tensorflow_text as text

In [24]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "p"

In [25]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [26]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

In [27]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [28]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [29]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [30]:
bert_model = hub.KerasLayer(encoder_url)

In [31]:
bert_results = bert_model(text_preprocessed)

In [32]:
bert_results.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'default', 'pooled_output'])

In [33]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292029,  0.08567813,  0.14476839, ..., -0.09677113,
          0.08722142,  0.07711106],
        [ 0.1783941 , -0.19006114,  0.5034949 , ..., -0.05869768,
          0.3271709 , -0.15578549],
        [ 0.18701488, -0.433888  , -0.48875114, ..., -0.15502754,
          0.00145118, -0.24470991],
        ...,
        [ 0.12083052,  0.12884241,  0.46453553, ...,  0.07375544,
          0.17441958,  0.16522089],
        [ 0.07967869, -0.01190678,  0.50225437, ...,  0.1377776 ,
          0.21002229,  0.00624557],
        [-0.07212676, -0.28303453,  0.5903338 , ...,  0.47551933,
          0.166685  , -0.08920376]],

       [[-0.07900578,  0.36335114, -0.21101592, ..., -0.17183757,
          0.16299775,  0.6724263 ],
        [ 0.2788361 ,  0.43716276, -0.35764754, ..., -0.04463636,
          0.3831522 ,  0.58879834],
        [ 1.2037675 ,  1.0727024 ,  0.48408723, ...,  0.24921031,
          0.40730965,  0.4048181 ],
        ...,

In [34]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917742 , -0.21411937,  0.49769446, ...,  0.24465124,
        -0.47334486,  0.8175871 ],
       [-0.91712314, -0.47935176, -0.7865699 , ..., -0.61751753,
        -0.71026856,  0.92184305]], dtype=float32)>

In [35]:
len(bert_results['encoder_outputs'])

12

In [36]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

In [37]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901418,  0.00644741, -0.03614967, ...,  0.0499962 ,
           0.06149203, -0.02657553],
         [ 1.1753381 ,  1.2140785 ,  1.1569979 , ...,  0.11634357,
          -0.35855347, -0.4049017 ],
         [ 0.03859048,  0.5387    , -0.21089832, ...,  0.21858203,
           0.72601664, -1.1158605 ],
         ...,
         [-0.07587032, -0.25421897,  0.7075512 , ...,  0.5054202 ,
          -0.18878655,  0.15028352],
         [-0.16066608, -0.28089693,  0.5759709 , ...,  0.5275853 ,
          -0.11141373,  0.02887543],
         [-0.04428176, -0.20279588,  0.59093547, ...,  0.8133835 ,
          -0.39075813, -0.02601737]],
 
        [[ 0.18903577,  0.02752553, -0.06513748, ..., -0.00620204,
           0.15053879,  0.03165438],
         [ 0.591615  ,  0.75891346, -0.07240663, ...,  0.6190396 ,
           0.82928914,  0.1616197 ],
         [ 1.446083  ,  0.44602585,  0.4099028 , ...,  0.48255908,
           0.62691116,  0.13