In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[29, 12]

In [2]:
vocab_size = 30 
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[21, 29], [14, 4], [3, 18], [7, 13, 17], [20, 14, 4], [27, 29], [28, 14, 12], [12, 2], [12, 7], [22, 19]]


In [3]:
encoded_reviews

[[21, 29],
 [14, 4],
 [3, 18],
 [7, 13, 17],
 [20, 14, 4],
 [27, 29],
 [28, 14, 12],
 [12, 2],
 [12, 7],
 [22, 19]]

In [8]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length,padding = 'post')
padded_reviews

array([[21, 29,  0],
       [14,  4,  0],
       [ 3, 18,  0],
       [ 7, 13, 17],
       [20, 14,  4],
       [27, 29,  0],
       [28, 14, 12],
       [12,  2,  0],
       [12,  7,  0],
       [22, 19,  0]])

In [12]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length = max_length, name ="embedding"))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [13]:
x = padded_reviews
y = sentiment

In [14]:
model.compile(optimizer = 'adam', loss="binary_crossentropy",metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 5)              150       
_________________________________________________________________
flatten (Flatten)            (None, 15)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 16        
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(x,y,epochs=50,verbose = 0)

In [20]:
loss, accuracy = model.evaluate(x,y)
accuracy

1/1 [==============================] - 0s 18ms/step - loss: 0.5077 - accuracy: 1.0000


1.0

In [21]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [22]:
weights[13]

array([ 0.06183215,  0.10162792,  0.08300316, -0.10905617, -0.09255205],
      dtype=float32)

In [23]:
weights[4]

array([ 0.07900309,  0.11920428, -0.0474247 , -0.13351323, -0.08875486],
      dtype=float32)

In [24]:
weights[16]

array([ 0.02344468, -0.04690675, -0.03673563,  0.04597246,  0.02832255],
      dtype=float32)