In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [9]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):#zip will take one value from yt=y_true,yp=y_predicted in each itration  
        total_error+=abs(yt-yp)#+= add
    print("Total error",total_error)
    mae = total_error/len(y_true)
    print('MAE:',mae)
    return mae

In [10]:
mae(y_true,y_predicted)

Total error 2.5
MAE: 0.5


0.5

In [11]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [27]:
np.log([0.0000000001])

array([-23.02585093])

In [28]:
eplison=1e-15

In [29]:
y_predicted_new = [max(i,eplison) for i in y_predicted]#max(i,eplison) will substitue the 0 value with epsilon and for 1 it is min
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [30]:
y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [31]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [33]:
np.log(y_predicted)

C:\Users\nafissaad\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([  0.,   0., -inf, -inf,   0.])

In [35]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [38]:
def log_loss(y_true,y_predicted):
    y_predicted_new = [max(i,eplison) for i in y_predicted]
    y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [39]:
log_loss(y_true,y_predicted)

17.2696280766844

In [40]:
#exercise
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])


In [41]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse


In [42]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

In [43]:
np.mean(np.square(y_true-y_predicted))

0.366