In [1]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9611111111111111

In [4]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9685185185185186

In [10]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print (train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train, y_train)
    return model.score(X_test,y_test)

In [14]:
get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test)

0.9611111111111111

In [16]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9833333333333333

In [17]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [18]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
    digits.target[train_index], digits.target[test_index]
    
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test ))
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr',max_iter=10000), X_train, X_test, y_train, y_test ))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test ))

In [19]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [22]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [23]:
scores_rf

[0.9232053422370617, 0.9449081803005008, 0.9181969949916527]

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data,digits.target)

array([0.91388889, 0.91666667, 0.9637883 , 0.95264624, 0.91643454])

In [27]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data,digits.target)

array([0.925     , 0.875     , 0.93871866, 0.93314763, 0.89693593])

In [28]:
#Exercise

In [44]:
from sklearn.datasets import load_iris
iris=load_iris()
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [37]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [46]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [50]:
cross_val_score(LogisticRegression(max_iter=10000),iris.data,iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])